### ISSUE TITLE
2 Spalten - Breitenverhätlnis

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021-blocks#1]
Bei 2 Spalten ist die linke Spalte breiter als die rechte, müsste jedoch 50/50% sein

![image](https://user-images.githubusercontent.com/46542480/51072763-592b5c80-1666-11e9-91fc-8791236b8600.png)

**Comment by angie-graphics** [comment]
die Breite ist anscheinend abhängig vom Inhalt, ist immer unterschiedlich. Dieser müsste fix sein

**Comment by dfringeli** [comment]
Yuppii
es isch sogar gange, ohni dass me alli blöck neu het miesse ifiege 👍 🥇

**Comment by angie-graphics** [comment]
seht guet us
