### ISSUE TITLE
News Beiträge

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021-blocks#10]
Wenn ich den Block "KTF Beiträge" auswähle erscheint folgende Fehlermeldung:

![image](https://user-images.githubusercontent.com/46542480/59087019-cc7a8700-8903-11e9-878d-66bbc339bcd5.png)

**Comment by dfringeli** [comment]
d'Ursach hanni gfunge: und zwar gits ä fehler, wenn d'kategorie glade werde.
Dr fehler chunt nit fo mir - dä chunt fo dr Wordpress API

Ig ha 2 möglichi Lösigsvorschläg:
1. wenn die fehler mäldig chunt, denn chame "Wiederherstellung versuchen" drucke und es lauft alles - sogar d'kategorie sii glade..
2. d'möglichkeit zum News nach kategorie z'filtere bimene News Block entferne - Mit dr Ahnahm, dass mirs nie brucht hei und nie werde bruche.

Du chasch säge wasi mache söll - oder au öppis ganz angeres.

**Comment by angie-graphics** [comment]
variante 2 - glaub das wärde mir nid bruchä ☺️

**Comment by dfringeli** [comment]
done und online

**Comment by angie-graphics** [comment]
yeah, danke
