### ISSUE TITLE
KTF Buttons

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021-blocks#11]
Der KTF Button erlaubt aktuell nur den Link auf eine Datei, jedoch nicht auf eine andere Seite:

![image](https://user-images.githubusercontent.com/46542480/59087094-0481ca00-8904-11e9-984e-9320203ba1fb.png)

Ich wollte nachschauen, wie das beim News-Archiv Button gemacht wurde, jedoch erscheint dieser nicht auf der Startseite im Backend.

**Comment by dfringeli** [comment]
man kann nun bei einem Button seine Funktion auswählen: Datei oder Seite
Bei der Datei hat man den Datei-Auswähler.
Und bei einer der Funktion Seite kann man den Titel der Seite und es zeigt Vorschläge an.
Have a look!

**Comment by angie-graphics** [comment]
perfekt, danke vielmals > schon im einsatz :-D

**Comment by dfringeli** [comment]
supper!
