### ISSUE TITLE
Collapse Block active

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021-blocks#12]
beim collapse block sind die aktiven buttons nicht mehr blau. 
evt. hat es was mit dem !important für generelle buttons zu tun?

**Comment by angie-graphics** [comment]
scheint in Chrome & FF zu funktionieren, jedoch in Safari und Edge nicht

**Comment by dfringeli** [comment]
Has gfixt und es isch ah däm gläge wäge important, Merci

**Comment by angie-graphics** [comment]
funktioniert! danke vill mol
