### ISSUE TITLE
Header-Slider

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021-blocks#13]
Ist es möglich dem Header-Slider zu sagen, wenn er nur eiin Bild enthält, soll er nicht sliden und keine Pfeile und Punkte anzeigen?

**Comment by dfringeli** [comment]
Ig ha dir ä Wallpaper Block erstellt. Dört chasch nur 1 Bild setze, defür säge öpp fade in effect und au d'Höchi vom Bild chasch setze. Es isch die ganzi Breiti gross und zentriert sich.
Bischpiel z'oberst uf der Testsite: https://ktf21.ch/?page_id=959

Zum ahluege, have fun und evtl. noh witteri wünsch

**Comment by angie-graphics** [comment]
grundsätzlich super.. nur obe de abstand isch z gross:

![grafik](https://user-images.githubusercontent.com/46542480/60176629-30afad00-9817-11e9-9dbf-cd5e1a024f31.png)

sött glich si wie bim slider

**Comment by dfringeli** [comment]
der Abstand stimmt nun, hab es gefunden.
Die alte Version des Blocks ist nun ungültig - aber ich nehme nicht an, dass du ihn schon überall verwendet hast? Falls Doch werd ich sie dir erneuern 😉

**Comment by angie-graphics** [comment]
ja, stimmt so. ne nur auf der testseite. ;-)

danke dir
