### ISSUE TITLE
Kontaktformular

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021-blocks#2]
Kannst du bitte noch ein Plugin installieren, mit welchem man Kontakftformulare bauen kann?
http://dfringel.cyon.link/kontakt/

**Comment by angie-graphics** [comment]
Kannst du bitte die Pflichtfeld-Warnungen auf hochdeutsch schreiben?

**Comment by angie-graphics** [comment]
jetzt: Das Fäld muess usgfüllt sii!

neu: Dieses Feld muss ausgefüllt werden!

**Comment by angie-graphics** [comment]
und de button no im richtige style.. denn erledigt :-)

**Comment by dfringeli** [comment]
done: https://ktf21.ch/kontakt/
