### ISSUE TITLE
Slider-Element für Redakteure

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021-blocks#3]
Wir brauchen noch einen Block, um den Slider einfügen zu können. Die Redakteure müssten die Bilder dazu selber einfügen können.

**Comment by dfringeli** [comment]
Ready for feedback

**Comment by angie-graphics** [comment]
bedienung im backend ist tipp top, jedoch wird bei mir immer nur das 1. bild im frontend angezeigt, egal ob ich warte oder mit den bullets weitergehe.. siehe https://ktf21.ch/wettbewerb/

was habe ich falsch gemacht? :-)

**Comment by dfringeli** [comment]
hab ein JavaScript File falsch geladen und hab es gefixt https://ktf21.ch/wettbewerb/

**Comment by angie-graphics** [comment]
ich hab das element nochmals gelöscht und neu hinzugefügt.. immer noch dasselbe problem.. wird nur das 1. bild angezeigt :-/

**Comment by dfringeli** [comment]
Du hast vermutlich die Editor Seite von Wettbewerb noch offen gehabt und ohne Refresh des Editors den Slider-Block entfernt und neu hinzugefügt. Dabei ist noch der alte Block mit der Fehlreferenzierung geladen und auch so beim Aktualisieren gespeichert worden. Da bin ich auch schon ein paar mal hineingelaufen..

Falls dies nicht das Probelm war, so solltest Du in der Console einen 404 Fehler des gesuchten Scripts finden. Dann suche ich nochmals das Problem zu beheben.

**Comment by angie-graphics** [comment]
war nochmals falsch.. dann hab ich herausgefunden, dass bei "meist genutzte elemente" noch das alte drin ist. habs nun hingekriegt. fantastisch! dankeschööön
