### ISSUE TITLE
Button-Block

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021-blocks#5]
- Die KTF Farben zur Auswahl anbieten
- Hover-Effekte (abdunkeln) einbauen

blau: #00cfff
blau hover: #3ca6cd

grün: #a3d01e
grün hover: #8faf1c

schwarz: #000000
schwarz hover: #2f3030

**Comment by dfringeli** [comment]
Bereit zum Anschauen
Beispiel auf https://ktf21.ch/sponsoring-partner/

**Comment by angie-graphics** [comment]
perfekt! danke :-)
