### ISSUE TITLE
Spalten-Titel Ausrichtung

### ISSUE THREAD

**Issue by ghost** [dfringeli/ktf2021-blocks#6]
Der Spalten-Titel kann nicht ausgerichtet werden, wird immer zentriert angezeigt, was ja OK ist.
Jedoch auf mobile wird dieser linksbündig angezeigt und man kann dies nicht anpassen:

![img_5671](https://user-images.githubusercontent.com/46542480/51186149-36ed4500-18d9-11e9-9834-85abd4e4b8e8.PNG)

**Comment by dfringeli** [comment]
es isch passiert - die änderig fiehrt zun lösche/neu ihfiege fo allne columns-blöck...

**Comment by angie-graphics** [comment]
was heisst das jetzt?  i cha alli site nomol neu mache? :-O

**Comment by angie-graphics** [comment]
hesch kei test-system wo du zerst luegsch was mit dr änderig passiere wird? backup oder sowas? :-)

**Comment by dfringeli** [comment]
Lokal eifach :smile:
Aber wenn mes will, denn chames nit umgo..

**Comment by angie-graphics** [comment]
aber das cha jo nid si.. dass alli lüt wo wordpress site hei ständig müsse de ganz content nomol neuu erfasse, wenn sie öbis dra ändere.. isch wordpress do so unflexibel? :-O

**Comment by dfringeli** [comment]
Abr das wird ig mache - hanni mol imene mail gschriebe kah..
Negst wuche
