### ISSUE TITLE
Collapse Block

### ISSUE THREAD

**Issue by dfringeli** [dfringeli/ktf2021-blocks#8]
Collapse Block
Links klicken und dann rechts den entsprechenden Text-Inhalt - wie im Prototyp:
![image](https://user-images.githubusercontent.com/33898687/58151976-9aaec280-7c6b-11e9-9568-c52e70be1fe0.png)

**Comment by dfringeli** [comment]
Ist erstellt - Beispiel unter https://ktf21.ch/testseite/
Desktop ist es so, wie im Prototyp (siehe Screenshot)
Auf Mobile hab ich es als Accordion realisiert:
![image](https://user-images.githubusercontent.com/33898687/58153065-756f8380-7c6e-11e9-8e4e-ff72688dad38.png)

Have fun!

**Comment by angie-graphics** [comment]
geile sache! hab noch ein paar schönheitssachen ;-)

1. beim klicken der buttons hüpfen diese irgendwie unnötig

2. der aktive button sollte eine andere farbe habe, siehe prototyp:

![image](https://user-images.githubusercontent.com/46542480/58351826-2b52f180-7e6a-11e9-9763-09446227b878.png)


3. der text sollte keinen rahmen haben auf desktop > mobile ist es so ok

4. der text sollte weiter rechts anfangen und nicht so nahe an den buttons kleben. also eigentlich wie wenn das ganze im 2 spalten element wäre.. buttons in der 1. spalte und text in der 2. spalte.

ansonsten super gemacht! -> kann den block im backend jedoch nicht bearbeiten

**Comment by dfringeli** [comment]
1. fixed
2. done
3. done
4. done
Nun solltest Du ih auch bearbeiten können
Bitte bei i.O. Issue schliessen 👍

**Comment by angie-graphics** [comment]
geilomat - ich liebe es! :-) Danke vielmals

**Comment by angie-graphics** [comment]
ich habe hier keinen schliessen button -> du kannst das ticket abschliessen
